name: cicd pipeline

# Trigger workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.sjmandall}}
          password: ${{ secrets.sjhe2415 }}

      # 3️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.sjmandall }}/rkg-flask:latest .

      # 4️⃣ Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.sjmandall }}/rkg-flask:latest

